language: c
cache: ccache
branches:
    except:
        - /appveyor.*/

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env: DISTRO=xcode9.2

install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install ccache

script:
    - ./test/scripts/build-travis-osx.sh
    - ccache -s
